### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [nikelone/beautiful-cookie-consent-gtm-variable-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1. The documentation [url](https://nikel.co/how-tos/beautiful-cookie-banner-how-to-configure-google-tagmanager) provided in the manifest file is not valid. It is showing "404 Oops! That page can’t be found." error to the user.

**Comment by nikelone** [comment]
Hi, thx for the hint. It is fixed now and the page is available.

**Comment by nikelone** [comment]
@praveena-pappu Hi it is fixed now. Thanks for the hint.

**Comment by nikelone** [comment]
Hi,

this is fixed. happy to get a 2nd review.

Thanks a lot.

Regards
Nikel
